name: "srinil-stay"

services:
  postgres:
    image: docker.io/postgres:18-alpine
    container_name: srinil-stay-postgres
    environment:
      POSTGRES_DB: srinil-stay
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - srinil-stay-network
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  pgdata:
    name: srinil-stay-pgdata

networks:
  srinil-stay-network:
    name: srinil-stay-network
